// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/Bo0km4n/go-protobuf-ref-sample/team/handler/grpc/team/team.proto

package team

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import user "github.com/Bo0km4n/go-protobuf-ref-sample/user/handler/grpc/user"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Team struct {
	Id                   int64       `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Users                *user.Users `protobuf:"bytes,3,opt,name=users" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Team) Reset()         { *m = Team{} }
func (m *Team) String() string { return proto.CompactTextString(m) }
func (*Team) ProtoMessage()    {}
func (*Team) Descriptor() ([]byte, []int) {
	return fileDescriptor_team_f996cb500f404d22, []int{0}
}
func (m *Team) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Team.Unmarshal(m, b)
}
func (m *Team) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Team.Marshal(b, m, deterministic)
}
func (dst *Team) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Team.Merge(dst, src)
}
func (m *Team) XXX_Size() int {
	return xxx_messageInfo_Team.Size(m)
}
func (m *Team) XXX_DiscardUnknown() {
	xxx_messageInfo_Team.DiscardUnknown(m)
}

var xxx_messageInfo_Team proto.InternalMessageInfo

func (m *Team) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Team) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Team) GetUsers() *user.Users {
	if m != nil {
		return m.Users
	}
	return nil
}

type InviteRequest struct {
	Team                 string   `protobuf:"bytes,1,opt,name=team" json:"team,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InviteRequest) Reset()         { *m = InviteRequest{} }
func (m *InviteRequest) String() string { return proto.CompactTextString(m) }
func (*InviteRequest) ProtoMessage()    {}
func (*InviteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_team_f996cb500f404d22, []int{1}
}
func (m *InviteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InviteRequest.Unmarshal(m, b)
}
func (m *InviteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InviteRequest.Marshal(b, m, deterministic)
}
func (dst *InviteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InviteRequest.Merge(dst, src)
}
func (m *InviteRequest) XXX_Size() int {
	return xxx_messageInfo_InviteRequest.Size(m)
}
func (m *InviteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InviteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InviteRequest proto.InternalMessageInfo

func (m *InviteRequest) GetTeam() string {
	if m != nil {
		return m.Team
	}
	return ""
}

func (m *InviteRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *InviteRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ActivateRequest struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivateRequest) Reset()         { *m = ActivateRequest{} }
func (m *ActivateRequest) String() string { return proto.CompactTextString(m) }
func (*ActivateRequest) ProtoMessage()    {}
func (*ActivateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_team_f996cb500f404d22, []int{2}
}
func (m *ActivateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivateRequest.Unmarshal(m, b)
}
func (m *ActivateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivateRequest.Marshal(b, m, deterministic)
}
func (dst *ActivateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivateRequest.Merge(dst, src)
}
func (m *ActivateRequest) XXX_Size() int {
	return xxx_messageInfo_ActivateRequest.Size(m)
}
func (m *ActivateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActivateRequest proto.InternalMessageInfo

func (m *ActivateRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type ActivateResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivateResponse) Reset()         { *m = ActivateResponse{} }
func (m *ActivateResponse) String() string { return proto.CompactTextString(m) }
func (*ActivateResponse) ProtoMessage()    {}
func (*ActivateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_team_f996cb500f404d22, []int{3}
}
func (m *ActivateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivateResponse.Unmarshal(m, b)
}
func (m *ActivateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivateResponse.Marshal(b, m, deterministic)
}
func (dst *ActivateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivateResponse.Merge(dst, src)
}
func (m *ActivateResponse) XXX_Size() int {
	return xxx_messageInfo_ActivateResponse.Size(m)
}
func (m *ActivateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ActivateResponse proto.InternalMessageInfo

func (m *ActivateResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_team_f996cb500f404d22, []int{4}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Team)(nil), "team.Team")
	proto.RegisterType((*InviteRequest)(nil), "team.InviteRequest")
	proto.RegisterType((*ActivateRequest)(nil), "team.ActivateRequest")
	proto.RegisterType((*ActivateResponse)(nil), "team.ActivateResponse")
	proto.RegisterType((*Empty)(nil), "team.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TeamAPIClient is the client API for TeamAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TeamAPIClient interface {
}

type teamAPIClient struct {
	cc *grpc.ClientConn
}

func NewTeamAPIClient(cc *grpc.ClientConn) TeamAPIClient {
	return &teamAPIClient{cc}
}

// Server API for TeamAPI service

type TeamAPIServer interface {
}

func RegisterTeamAPIServer(s *grpc.Server, srv TeamAPIServer) {
	s.RegisterService(&_TeamAPI_serviceDesc, srv)
}

var _TeamAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "team.TeamAPI",
	HandlerType: (*TeamAPIServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "github.com/Bo0km4n/go-protobuf-ref-sample/team/handler/grpc/team/team.proto",
}

func init() {
	proto.RegisterFile("github.com/Bo0km4n/go-protobuf-ref-sample/team/handler/grpc/team/team.proto", fileDescriptor_team_f996cb500f404d22)
}

var fileDescriptor_team_f996cb500f404d22 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0x5f, 0x4b, 0xc3, 0x30,
	0x14, 0xc5, 0xe9, 0xfe, 0x38, 0x7b, 0x87, 0x7f, 0x08, 0x3e, 0x8c, 0x3d, 0xcd, 0x82, 0xd0, 0x97,
	0xb6, 0x32, 0xfd, 0x02, 0x13, 0x7c, 0x18, 0x22, 0x48, 0x70, 0x1f, 0x20, 0x6d, 0xef, 0xba, 0xb0,
	0xe6, 0x8f, 0x49, 0x3a, 0xf1, 0xdb, 0x4b, 0xd2, 0xa9, 0xec, 0xd1, 0x97, 0xcb, 0x39, 0xa7, 0xa7,
	0xbf, 0x9b, 0x04, 0x5e, 0x1a, 0xee, 0x76, 0x5d, 0x99, 0x57, 0x4a, 0x14, 0x4f, 0xea, 0x7e, 0x2f,
	0x1e, 0x65, 0xd1, 0xa8, 0x4c, 0x1b, 0xe5, 0x54, 0xd9, 0x6d, 0x33, 0x83, 0xdb, 0xcc, 0x32, 0xa1,
	0x5b, 0x2c, 0x1c, 0x32, 0x51, 0xec, 0x98, 0xac, 0x5b, 0x34, 0x45, 0x63, 0x74, 0xd5, 0x27, 0x7e,
	0xe4, 0xa1, 0x4f, 0x46, 0x5e, 0xcf, 0xff, 0x81, 0xec, 0x2c, 0x9a, 0x53, 0x64, 0x48, 0xfc, 0xe8,
	0x91, 0xc9, 0x2b, 0x8c, 0xde, 0x91, 0x09, 0x72, 0x09, 0x03, 0x5e, 0xcf, 0xa2, 0x45, 0x94, 0x0e,
	0xe9, 0x80, 0xd7, 0x84, 0xc0, 0x48, 0x32, 0x81, 0xb3, 0xc1, 0x22, 0x4a, 0x63, 0x1a, 0x34, 0xb9,
	0x85, 0xb1, 0xff, 0xd3, 0xce, 0x86, 0x8b, 0x28, 0x9d, 0x2e, 0xa7, 0x79, 0xe0, 0x6c, 0x7c, 0x44,
	0xfb, 0x2f, 0xc9, 0x06, 0x2e, 0xd6, 0xf2, 0xc0, 0x1d, 0x52, 0xfc, 0xe8, 0xd0, 0x3a, 0xcf, 0xf1,
	0x87, 0x0e, 0xe4, 0x98, 0x06, 0x4d, 0x6e, 0x60, 0x8c, 0x82, 0xf1, 0xf6, 0x08, 0xef, 0x0d, 0x99,
	0xc3, 0xb9, 0x66, 0xd6, 0x7e, 0x2a, 0x53, 0x87, 0x05, 0x31, 0xfd, 0xf5, 0xc9, 0x1d, 0x5c, 0xad,
	0x2a, 0xc7, 0x0f, 0xec, 0x04, 0x5c, 0xa9, 0x1a, 0x7f, 0xc0, 0x5e, 0x27, 0x29, 0x5c, 0xff, 0xd5,
	0xac, 0x56, 0xd2, 0xa2, 0x5f, 0xe6, 0xd4, 0x1e, 0xe5, 0xb1, 0xd8, 0x9b, 0x64, 0x02, 0xe3, 0x67,
	0xa1, 0xdd, 0xd7, 0x32, 0x86, 0x89, 0xbf, 0xff, 0xea, 0x6d, 0x5d, 0x9e, 0x85, 0x17, 0x79, 0xf8,
	0x0e, 0x00, 0x00, 0xff, 0xff, 0xa9, 0x56, 0x3f, 0xea, 0xb3, 0x01, 0x00, 0x00,
}
